CREATE VIEW AOLND AS
SELECT
    FACTS_EXTENDED.QUERYID AS QUERYID,
    FACTS_EXTENDED.TIMEID AS TIMEID,
    FACTS_EXTENDED.ANONID AS ANONID,
    FACTS_EXTENDED.URLID AS URLID,
    FACTS_EXTENDED.NDCID AS NDCID,
    FACTS_EXTENDED.IRANK,
    FACTS_EXTENDED.CLICK
FROM
    "FACTS_EXTENDED"
LEFT JOIN
    "ANONIDDIM"
ON
    "ANONIDDIM"."ID" = "FACTS_EXTENDED"."ANONID"
LEFT JOIN
    "TIMEDIM"
ON
    "TIMEDIM"."ID" = "FACTS_EXTENDED"."TIMEID"
LEFT JOIN
    "QUERYDIM"
ON
    "QUERYDIM"."ID" = "FACTS_EXTENDED"."QUERYID"
LEFT JOIN
    "NDCDIM"
ON
    "NDCDIM"."ID" = "FACTS_EXTENDED"."NDCID"
LEFT JOIN
    "URLDIM"
ON
    "URLDIM"."ID" = "FACTS_EXTENDED"."URLID"
WHERE
    "FACTS_EXTENDED".NDCID != -1;