WITH FACTS_2 AS (
    SELECT
        "FACTS".ANONID AS ANONID,
        "FACTS".TIMEID AS TIMEID,
        "FACTS".QUERYID AS QUERYID,
        "FACTS".URLID AS URLID,
        "QUERYDIM_EXTENDED"."Query" AS QUERY,
        "QUERYDIM_EXTENDED"."Category" AS CATEGORY,
        "NDCDIM"."ID" AS NDCID
    FROM
        "FACTS"
    LEFT JOIN
        "ANONIDDIM"
    ON
        "ANONIDDIM"."ID" = "FACTS"."ANONID"
    LEFT JOIN
        "TIMEDIM"
    ON
        "TIMEDIM"."ID" = "FACTS"."TIMEID"
    LEFT JOIN
        "QUERYDIM_EXTENDED"
    ON
        "QUERYDIM_EXTENDED"."ID" = "FACTS"."QUERYID"
    LEFT JOIN
        "NDCDIM"
    ON
        "QUERYDIM_EXTENDED"."Category" = "NDCDIM"."CATEGORY"
    LEFT JOIN
        "URLDIM"
    ON
        "URLDIM"."ID" = "FACTS"."URLID"
);
UPDATE
    FACTS
SET
    FACTS.NDCID = FACTS_2.NDCID
WHERE
    FACTS.ANONID = FACTS_2.ANONID
    AND FACTS.TIMEID = FACTS_2.TIMEID
    AND FACTS.QUERYID = FACTS_2.QUERYID
    AND FACTS.URLID = FACTS_2.URLID;