SELECT
    QG_QUERY_0314.QUERY QUERY,
    QG_QUERY_0314.FREQ FREQ,
    DENSE_RANK() OVER ( ORDER BY QG_QUERY_0314.FREQ DESC ) AS RANK
FROM
    QG_QUERY_0314
ORDER BY
    RANK;

SELECT
    CG_QUERY_0314.CATEGORY CATEGORY,
    CG_QUERY_0314.FREQ FREQ,
    DENSE_RANK() OVER ( ORDER BY CG_QUERY_0314.FREQ DESC ) AS RANK
FROM
    CG_QUERY_0314
ORDER BY
    RANK;