SELECT
    TD."MONTH" AS MONTH_OF_THE_YEAR, TD.DAY_OF_THE_MONTH, COUNT(AOLND.NDCID) AS "COUNT"
FROM AOLND, TIMEDIM TD
WHERE
    TD.ID = AOLND.TIMEID
GROUP BY
    ROLLUP (TD."MONTH", TD."DAY_OF_THE_MONTH")
ORDER BY MONTH(TO_DATE(TD."MONTH", 'MONTH')), TD."DAY_OF_THE_MONTH";